### ISSUE TITLE
Add Wordpress GIF integration

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/optimole-wp#126]
After #124 is done

We should have a toggle inside the plugin dashboard to toggle if GIF `<img/>` tag should be replaced with `<video/>` tag. If check do the replacement else work as before.

**Comment by selul** [comment]
some things that we can improve:

- [ ] Lazyload on GIF is [useless](https://mlnbfnxyor9y.i.optimole.com/w:10 24/h:635/q:eco/http://testing.optimole.com/wp-content/uploads/2019/09/gutenberg-guide-update-oct-1.gif), we should use here the generic placeholder when the gif is encountered and lazyload is set. 
- [ ] Make sure to add a unit test for the upper case.
- [ ] Let's move the toggle for gif->video to Compression tab instead of the general.
- [ ] Autoscale seems to trigger on GIF, it should ignore this as we are not able to do exact size for GIFs. We can do this by adding a lazyload only class for the gif images, which library should lazyload but not scale.

**Comment by selul** [comment]
Why ? We already have the mechanism in the lib to do this.

**Comment by selul** [comment]
another one: 

- [ ] http://testing.optimole.com/gif-test/ here the poster is using png instead of webp in chrome.
