### ISSUE TITLE
fail to lazyload specific images

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#137]
Checking this URL https://demo.themeisle.com/neve-pro/ it seems this area fails to have the lazyload applied http://snpy.in/9jJRTs

The strange thing is that only the first image from the list has the lazyload, rest of them is missing it. 

Any clue what it could be?

**Comment by GrigoreMihai** [comment]
it seems like if the image url has something like '?whatever' after the extension the lazyload fails for that url

**Comment by selul** [comment]
@GrigoreMihai what has to do with this bug? None of the images have any query string in URL, and we already treat this case and is working fine. 

here you have the test case aswell: 
https://github.com/Codeinwp/optimole-wp/blob/master/tests/test-lazyload.php#L103

**Comment by GrigoreMihai** [comment]
@selul  If the original src of the images from that page don't have any query string in them then it has nothing to do with the bug (i didn't see the original src of those images so i was just asking) 

For images with query i tested it on a page with the plugin on and it doesn't apply lazyload to them, because it fails to get the extension from urls that have query (that is why the test works), i thought that the same issue might also be on that page

**Comment by selul** [comment]
Ok, then why the test is passing if you think we have an issue ?

**Comment by GrigoreMihai** [comment]
It passes because the part that handles the lazyload can't read the extension of an image that has query string so the lazyload fails as expected on that test 

https://github.com/Codeinwp/optimole-wp/blob/aaf2815dc212728e541bde6aaca69e801b0e84f6/inc/lazyload_replacer.php#L203

**Comment by selul** [comment]
Ok, we can create a separate issue for this case, this issue is still not covered with that fix.

**Comment by selul** [comment]
a follow up on this, we can still this happening here https://demo.themeisle.com/neve-pro-old/

**Comment by preda-bogdan** [comment]
Seams to be fixed in the latest releases feel free to open it again if you manage to encounter this bug again.
