### ISSUE TITLE
own carousel logos distorted

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#260]
**Describe the bug**
The replaced by optimole images look distorted here: https://www.dropbox.com/s/4zet5fh2i04l6ud/Screenshot%202020-07-18%2011.38.47.png?dl=0, if I remove the optimole processing ( see Kellogg), the logo looks good.

**To Reproduce**
1. Go to https://www.chitkara.edu.in
2. Scroll to the logos section
3. Try to remove optimole processing

Optimole generated image: https://mlqhfjp0jp4l.i.optimole.com/b2Vu344.L-3f~2730/w:107/h:27/q:auto/https://www.chitkara.edu.in/wp-content/themes/chitkara/images/cbs-hm/2019/coca-cola-logo.png vs original image: https://www.chitkara.edu.in/wp-content/themes/chitkara/images/cbs-hm/2019/coca-cola-logo.png

It seems that we have a problem with data-height, which we set too small

**Screenshots**

**Expected behavior**
I would expect fo the image to look just as good.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only Optimole plugin is active.
- [ x] I can reproduce this bug consistently using the steps above.

cc @selul It would be a best practice to pro-actively check major sites added to optimole on our end for glitches, I guess many times customers try, see issues and quit ( might be weird processing, missing images etc). If there is a problem on their side and is a big site like this one, we can proactively reach out and propose them to fix if is possible or explain how they can improve, often I don't think they would report.

**Comment by GrigoreMihai** [comment]
The height is to small because the width and height attributes of the 'img' tag are not set with respect to aspect ratio of the image and we are using those values when calculating the dimensions to scale at (i.e original image is 112x47 and tag attributes are set to 278x72, it should be set to 278x116 to keep aspect ratio, the 27 height results after computing 107/278*72, the correct value would be 44(=107/278*166) for the given height (107), which we would correctly calculate if the attributes would be set correct)

**Comment by ineagu** [comment]
I would still feel more comfortable if at least for PRO users, when they register the site with optimole, we schedule a test speed + screenshot and after registration another one, when there are differences we can think on some manual/automated flows to inform & help users.
