### ISSUE TITLE
e2e tests workflow is broken

### ISSUE THREAD

**Issue by selul** [Codeinwp/optimole-wp#347]
**Describe the bug**
@gutoslv @GrigoreMihai seems like the most recent build of the plugin https://github.com/Codeinwp/optimole-wp/pull/342/checks?check_run_id=2115001329 has some issues with the e2e routine by throwing an error related to the video recording.

Could you please help me fix the issue??

**Comment by GrigoreMihai** [comment]
It was caused by the latest version of chrome, for now I manually set the chrome version to 87. They fixed the issue in the next version of cypress https://github.com/cypress-io/cypress/issues/3491. Once the action we use for cypress will update the cypress version we should be able to remove the restriction on chrome.
