### ISSUE TITLE
Error about deprecated function with PHP 8

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/optimole-wp#359]
**Describe the bug**
Two users reported that with PHP 8 they get this error on the Optimole's plugin page:

Deprecated: usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /home/bihelek/naguibihelek.com/wp-content/plugins/optimole-wp/vendor/codeinwp/themeisle-sdk/src/Modules/Rollback.php on line 82

I'm not able to replicate this issue but maybe we can analyse what are the values that are passed to the function to better understand when this error can be thrown? (I wasn't able to do so).

User in this thread provided all the configuration settings that he has:
https://wordpress.org/support/topic/deprecated-error-when-using-php-8/#post-14314197

Also reported here - https://secure.helpscout.net/conversation/1494129997/276271/

**To Reproduce**
I'm not able to reproduce this error.

**Screenshots**
No screenshots.

**Expected behavior**
No error.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only Optimole plugin is active.
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
 WordPress Version: 5.7.1 
 Optimole Version: 3.0.1
 PHP versions: 8
</details>

**Comment by preda-bogdan** [comment]
Hello,

The notice comes from `themeisle-sdk` here: https://github.com/Codeinwp/themeisle-sdk/blob/aeef3f159c1b35451d87672b6984ccde36c0d21d/src/Modules/Rollback.php#L346

We should change this to `return (int) version_compare( $b['version'], $a['version'] );` as the `usort` function expects an `integer` instead of a `bool` from the callback function.

I've also opened an issue here: https://github.com/Codeinwp/themeisle-sdk/issues/102

I will submit a fix for this.

**Comment by selul** [comment]
it's already fixed there, we just need to update the SDK
