### ISSUE TITLE
Some users are having the warning errors for strpos() function

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/optimole-wp#572]
### Description

Since the last update two of our users have shared that they are getting an error on their site - 

The error message states that -

`Warning: strpos(): Empty needle in /home/customer/www/antson.io/public_html/wp-content/plugins/optimole-wp/inc/url_replacer.php on line 154`

Any insights on this? what could be the cause of the issue? I have asked them to provide the details about their environment. I'll update the comment with the information after receiving from them.

### Step-by-step reproduction instructions

1. Install the latest version of Optimole.

More concrete replication steps: https://github.com/Codeinwp/optimole-wp/issues/572#issuecomment-1604450081

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2279816178/373980
https://secure.helpscout.net/conversation/2278907955/373872

### Is the issue you are reporting a regression

No

**Comment by abaicus** [comment]
I looked into this a bit. I can see that flushing the cache solved the issue in one instance from the two mentioned above, but it looks like image replacement might be disabled (URLs are loaded from the website itself, and our scripts are not loaded on the page, but the Optimole rest routes seem to exist).

For a new site, things are working fine for me. The other reported website serves images through optimole fine. 

Let's see if we get other reports on this, or if the second report comes back with more info @kushh23. 

---

Looking at the code and what we changed in the latest release, I can't see any change we've done that could trigger this. 

cc @Codeinwp/optimole feel free to chip in if you have any idea what could have caused this.

**Comment by kushh23** [comment]
@abaicus Yes, it seems that by flushing the cache, he meant to say that the error disappeared from his front end. He mentioned that the error persisted even after downgrading to a lower version and disabling the plugin.

Furthermore, it is true that he has not enabled the URL replacement, which is why there is no URL in the first place.

I'll let you know if they reply back. BTW does [this](https://secure.helpscout.net/conversation/2279700785/373961) also looks like the same case?

**Comment by abaicus** [comment]
@kushh23 got it. Sorry for misreading the message. 

In the last case you mentioned, it seems to be a conflict with another plugin based on the first part of the error:

`PHP message: Furnob_Resize.process() error: Image file does not exist (or is not an image): /www/gafurnituremart_767/public/wp-content/uploadshttps://mllykzfpjqgq.i.optimole.com/w:auto/h:auto/q:mauto/f:avif//2023/05/T834-8.jpg`

It looks like the Furnob_Resize.process() is executed on a weird path. I don't think it's tied to the latest update. I assume that this might from another plugin, but can't find a source for the code in the error.

**Comment by kushh23** [comment]
@abaicus Okay thanks for the insights, I'll try to get more information about the last case.

**Comment by abaicus** [comment]
@kushh23 I finally managed to replicate this thanks to @preda-bogdan, who bumped into it randomly. I managed to replicate it using PHP 7.4.33

Here's the way to replicate this:
- Have Elementor installed and create a page using it, containing an image;
- Have PHP 7.4 (I replicated it with PHP 7.4.33);
- Install and activate Optimole but don't connect it;

The error will appear on the Elementor page you created before. This seems to happen because we load compatibilities without checking that we're connected (case in which we don't have `Optml_Config::$service_url` defined).

This was also causing an issue when accessing the page with the `optml_off=yes` URL param still replacing some of the images we're handling through the compatibilities classes.

I will add the replication steps to the initial issue body and send in a PR to ensure that the compatibilities are loaded only when Optimole is connected.

**Comment by kushh23** [comment]
+1: https://secure.helpscout.net/conversation/2283728500/374491

**Comment by abaicus** [comment]
@kushh23 this should be solved. 👍🏻

**Comment by kushh23** [comment]
@abaicus, thanks for the update about this. I will follow up to the users who reported the error.
