### ISSUE TITLE
Add disabled state for other features, that are dependent on the Optimole main image service

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/optimole-wp#677]
### Description

As mentioned [here](https://github.com/Codeinwp/optimole-wp/issues/621#issuecomment-1731309617), Resize, Compres, Lazyload are dependent on the **Enable image replacement** feature. 

When this feature is Disabled - other features should also go in a disabled state, since those don't produce any changes.

This was the default behavior on the version 3.7.0 and below.

### Step-by-step reproduction instructions

1. Create a fresh WP Instance with Optimole 3.10.0
2. Activate the plugin with an account
3. Go to the Settings page > General
4. Disable the Enable image replacement feature
5. Go to the Advanced Tab
6. Notice that Resize, Lazyload, Compression - have options enabled, even if those are producing any changes

### Screenshots, screen recording, code snippet or Help Scout ticket

In the first part of the video I am using version 3.10.0, while in the final part I am testing with 3.7:
 

https://github.com/Codeinwp/optimole-wp/assets/52494172/63345a41-1ed7-4cc5-bdd6-d7ccdd236f7f

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
@abaicus, on your 2nd point:

> Also, we should somehow make the user aware that this setting is the one that disables the others.

We don't put those features in disabled state, we just grey out features so if you enable main feature again they will be in the same state as they were before (with version 3.7). So we might not need to use additional information as it makes sense that greyed-out features don't work.

**Comment by abaicus** [comment]
My main concern is how a new user would tell that that is the main feature if he is unfamiliar with the plugin. This is the first setting they see, and if they toggle it off, other controls get disabled.  

This is a toggle to "turn off" all (or most) Optimole functionality. While going through the CSAT feedback, I found a user who was confused by exactly this approach: 

![image](https://github.com/Codeinwp/optimole-wp/assets/15010186/ac3602c7-588d-40e3-a85a-7308525479c6)

Even though we did this before, I believe it might be worth challenging it. 

It would be a good idea to bring more awareness to how that setting works and provide more insight when reviewing its title & description during #621 - I can see that Marius suggested naming it `Enable Optimole Image Handling` which is better.

Maybe instead of greying settings out, we can hide them from the UI so the focus remains on the main setting, which is kind of the "master toggle" of the functionality. That way, the only action a user can take is to enable the replacer.

Another idea would be to single it out as more of a global setting in the UI design.

Of course, @mghenciu if you think that this is good enough from a UX perspective, then probably we can go ahead and implement it the way it was before the react migration.

**Comment by vytisbulkevicius** [comment]
@abaicus,

Makes sense. As for making the title of the button more clean + its description to indicate that with this setting disabled other features of the plugin don't work either is a good idea, if we have that then no matter if we grey out or hide it should be clear. I still like the idea of greying out more than hiding. Then we can also have like a tooltip on hovering the greyed out feature that this feature is disabled because the main one is disabled.

**Comment by mghenciu** [comment]
Thank you for sharing ideas, guys.

There are multiple ways to look at this. In a way, from a design perspective - it would make things more clean, if we remove them, when the master switch is off.
But from another perspective, if we hide features - this would mean that we'll have to hide a lot of them, since most of the features are dependent on the master switch.

**So based on this, I would suggest we grey out the disabled features.** This should also help with feature Visibility, since even in disabled state, users can see them. Renaming the Master switch should also help. Additionally we can:
- use a title tag, that will appear when hovering on the Disabled features. I don't like that the title tag usually appears after a longer hover, but unfortunately - we can't control this from code.
- an extra thing (if you think that this is required), would be to have an informative notice unde the master switch, [like this](https://www.figma.com/file/m1h6vGH5aVujebg4lLdaOH/Optimole-Plugin-UI?type=design&node-id=4028-9699&mode=design&t=kD5s33z9l5DcnyGB-11):

<img width="1734" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/52494172/408f2c83-6384-439c-b13e-27990611d5a8">


Let me know your thoughts. 


___

On another note, another thing we also need to maybe address in another issue - is what happens when the master switch is turned off by the user. Currently there's no notice about something on the user end. Should we inform them about something? will Optimole work as expected if that feature is turned off?

**Comment by selul** [comment]
this is working fine now.
