### ISSUE TITLE
Disabling Scale Images & Lazy load in General won't affect the Lazyload panel

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#705]
We have the Scale images & lazy load feature in the General panel that activates scaling and lazy loading.
However, we also have a dedicated panel for lazy loading in Advanced > Lazy Load.

If Scale images & lazy load is disabled in General, the lazy load panel still functions independently. You can modify settings there even if the global lazy loading option is turned off. The Exclusions section no longer has a "Don't lazyload if" option in this case, so there it seems to be working fine.

Is this intended? Let me know what you think!

**Comment by vytisbulkevicius** [comment]
Before version 3.8 this was working differently - if you don't have **Scale images & lazy load** feature enabled in the General panel - the **Lazyload** tab is hidden (that's how it works with 3.7 version).

@abaicus, was this changed intentionally? Because if lazy-loading is disabled none of the features in that tab make effect

**Comment by abaicus** [comment]
I'm guessing this was accidental, similar to what happened in #677.
