### ISSUE TITLE
GIF not loaded when I enable GIF to video

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#711]
### Description

I enabled GIF to video conversion, and the video seems to be stuck on the first frame (blank screen).

### Step-by-step reproduction instructions

1. Insert a GIF on a webpage
2. Check if it's loaded properly
3. Go to settings > advanced > compression
4. Enable GIF to video conversion
5. Save the changes and check the page

### Screenshots, screen recording, code snippet or Help Scout ticket

Before:
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/6bb743fa-6c60-4ba0-b74b-7083ca24b8ec">

After:
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/82a037fc-1dda-44c1-882f-0548e6e289a7">

### Is the issue you are reporting a regression

No

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina It would be helpful if you could share a link to the page where you tested this. Also, it would be a good idea to share the GIF itself. 

I just tested this in production with a gif from my computer, and things work fine.

**Comment by AndreeaCristinaRadacina** [comment]
Here is the page - https://root.stefancoti.com/from-vine-to-glass-the-fascinating-journey-of-wine/

Here is the GIF:
![Oct-11-2023-16-05-37](https://github.com/Codeinwp/optimole-wp/assets/86592992/e715fc64-82c1-4bff-97f5-f89d2730d25c)

**Comment by abaicus** [comment]
Thank you for providing these! 👍🏻 

The image cannot be processed because it exceeds `IMGPROXY_MAX_SRC_RESOLUTION`. Even if we bump that up, processing would still time out. For smaller GIF files, things should work fine.

For reference, the GIF above has **75** frames at a resolution of _1678 × 752_. I don't know if we can do much in this context, but it might be worth investigating further. The response code seems to be 206 when using it as a video source. So it's partial content. In the `content-range` header, it seems like it misses one byte: `bytes 0-7402318/7402319`.

cc @Codeinwp/optimole, I don't know if you have any ideas regarding what might be happening here.

**Comment by AndreeaCristinaRadacina** [comment]
Thank you for checking!

If there are no other ideas, it would be good to specify some limits in the docs/descriptions.
