### ISSUE TITLE
Lazyloading exclusion not displayed as expected

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/optimole-wp#715]
Kanta reported that lazyloading exclusion doesn't work as mentioned in the docs. Once applied, the parameters don't include "data-opt-lazyload=false".

I tried on my end, and I can't replicate this. Do you know why this happens?
His website:
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/07b44ebb-23fe-40b0-b133-77788ca2b8ce">

My website:
<img width="1680" alt="image" src="https://github.com/Codeinwp/optimole-wp/assets/86592992/9a4f69ac-826c-4083-b2fb-0b3d84696fc8">

His details:
https://optimoledemo.instawp.xyz/wp-admin
helubecamo4855
DzCvjEt3JFkPTsANRuin

**Comment by abaicus** [comment]
@AndreeaCristinaRadacina The respective attribute appears upon resizing the window. I.e. when the inspector gets opened, the respective attribute might be added to all images, even if these are not lazy-loaded: https://github.com/Codeinwp/optimole_js_lib/blob/master/src/optimole/optimole_replacer.js#L136

Otherwise, these images are completely ignored on page load.

The data attribute that marks images for lazyload is the `data-opt-src` attribute. 

I will close this for now. Feel free to follow up if anything is unclear.
