### ISSUE TITLE
Upload of HEIC images doesn't work

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/optimole-wp#788]
### Description

A user asked if uploading HEIC files and automatically converting them to JPG is possible, as this feature is present in Shortpixel. I saw an [issue](https://github.com/Codeinwp/optimole-wp/issues/599) regarding this but it didn't work for me. I couldn't upload a HEIC file neither in WordPress library, Optimole WordPress library or Optimole Dashboard library https://vertis.d.pr/i/VxIO1I

Ticket - https://secure.helpscout.net/conversation/2566574189/413383/

### Step-by-step reproduction instructions

1. Try to upload a HEIC photo to Optimole library / WordPress library

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/VxIO1I

### Environment info

WordPress 6.5.2 / Optimole 3.12.6

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by selul** [comment]
Yes, this is not a bug; it's fine as we allow HEIC processing in the WP Plugin if the website allows uploading of the HEIC images. So before testing this, the site needs to allow uploading HEIC images without Optimole. Afterward, you can test if Optimole is optimizing this. 

Yes, I know that this is not ideal since it can be helpful to tweak the allowed files to be uploaded in WordPress but we can look in the future to add this.
