### ISSUE TITLE
quick view image not coming from optimole

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/optimole-wp#87]
@selul When you are here and trying quick view: https://demo.themeisle.com/shop-isle-pro/shop/, the images aren't loading through optimole, we probably need custom integration, but is a good example in case we can find something generic.

The plugin is : https://wordpress.org/plugins/yith-woocommerce-quick-view/ and is quite popular.

**Comment by selul** [comment]
@ineagu it does come but only when you are not logged. Because that's an ajax request, I have added the replacement handler to ajax responses only when you are not logged in because those ajax requests might be used in the admin area and we don't want to replace images in there. 

I can add for the quick view a more specific replacement which will target the logged in users for the yith ajax request.

**Comment by selul** [comment]
i have added a fix and patched the demo site too

**Comment by ineagu** [comment]
Ok, I am not sure if it should happen for logged-in too, as you find best
